### ISSUE TITLE
As a user I find it strange to have my offshore mega sculpts covering my region

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/Anaximander2#22]
The problem here is that the megasculpts doing the offshoring are larger than the region and their OBB covers the region entirely, resulting in a big single color blob.

**Comment by kf6kjg** [comment]
#8 would cover this, but in the interim Jim suggested simply eliminating all prims region size or larger: eg 256 or larger on any axis.

**Comment by appurist** [comment]
I wasn't actually suggesting if any axis was >= 256, but if both of the x and y were (looking down, after rotation).

We could probably filter if x and y were both >= 256 in the db (regardless of rotation) but if it passes that a second filter with an AABB box is probably needed to rule out filtering things like streets, sidewalks, prim rivers, etc. that might span a region width or length but still be narrow map-worthy objects.
