### ISSUE TITLE
As a land developer I find the maximum prim height to be very confusing

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/Anaximander2#23]
Currently the code draws all prims that fall under land height at prim origin + 256 meters.  This means the maximum height that drawn prims can be found at is a function of the terrain height.

This behavior comes from SL but is weird, like so many things LL.

**Comment by kf6kjg** [comment]
After a long talk with Jim, covering various calcs and tiering models, it was concluded that KISS applies.  Thus we settled on something like the region's minimum terrain height + 256m.  That will be different from region to region, but consistent within a region.
Benefits:
* Simple terrain edits don't often move the limit like they currently do.
* People can determine the limit easily.
* Extreme terrain heights, such as a mountain peak sim, don't cause the limit to go underground.

Negatives:
* Terrain editing can still change what prims show up where.  This leaves some griefing options, such as dropping a pit under a building and thus lowering the ceiling causing the map to change.
* Extreme changes in terrain height can cause places to have the limit below ground.

**Comment by appurist** [comment]
Thumbs up. 👍
